sudo: required
services:
        - docker

before_install:
  - docker build -t Ujjwalrajan/docker-aws -f Dockerfile.dev .

script:
  - docker run Ujjwalrajan/docker-aws npm run test -- --coverage





