sudo: required
services:
        - docker

before_install:
  - docker build -t ujjwalranjan/docker-aws -f Dockerfile.dev .

script:
  - docker run ujjwalranjan/docker-aws npm run test -- --coverage





